baseURL: https://johnr-damian.github.io
languageCode: en-US
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  author: John Rhey Damian
  description: a blog, and a portfolio
  github: https://github.com/johnr-damian
  gmail: johnr.damian98@gmail.com
taxonomies:
  #e.g. Animation, Artificial Intelligence, Geometry
  area: areas
  #e.g. Academic, Project, or Tutorial
  category: categories
  #e.g. C, C++, C#, Javascript, R
  language: languages
  #e.g. For Academic, Project, or Tutorial
  series: series
title: Algomorphogenesis